### ISSUE TITLE
covrpage

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackthreads#45]
At this point my best guess is that there's a missing token, or that the GITHUB_TOKEN isn't set to be able to write, or something along those lines. The covrpage vignette about CI is still Travis-focused, so I'm not sure. And to make sure that part is clear, I can't see settings/secrets/etc for this repo, so I can't fix that part.

**Comment by yonicd** [comment]
Covrpage works on gha. I’ll take care of it

**Comment by jonthegeek** [comment]
@yonicd It still hasn't ran via GHA on this repo (the files that are here are from me running it on my laptop). It works on slackcalls and I can't see a difference in the repo that would cause the failure. Maybe it's a setting?
